version: 2
references: 
  run_tests: &run_tests
    steps:
      - checkout
      - run: sudo npm install -g yarn
      - run: yarn install
      - run:
          name: test
          command: |
            mkdir -p ~/reports
            yarn test
      - store_test_results:
          path: ~/reports
          prefix: tests
      - store_artifacts:
          path: ~/reports
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

jobs:
  build-node4:
    docker:
      - image: circleci/node:4@sha256:b19c4f1659e0e27fe780b4ce956049c433775a6ae19cd51b619d1ba00a573454
    <<: *run_tests
  build-node6:
    docker:
      - image: circleci/node:6@sha256:8091d97bb55103f61ec55643466a72d390c366af1cb669b3c20e633e3236932a
    <<: *run_tests
  build-node8:
    docker:
      - image: circleci/node:latest@sha256:838bf44e30ae68dcb73d643137883ccdfa81a046eed91ae25c9c42a361d554fe
    <<: *run_tests
  release:
    docker: 
      - image: circleci/node:latest@sha256:838bf44e30ae68dcb73d643137883ccdfa81a046eed91ae25c9c42a361d554fe
    steps: 
      - checkout
      - run: sudo npm install -g yarn semantic-release@12.0.0
      - run: yarn install
      - run: semantic-release
      - run: yarn docs
      # needs proper NOW setup first
      # - run: yarn docs:publish

workflows:
  version: 2
  build:
    jobs:
      - build-node4
      - build-node6
      - build-node8
      - release:
          requires: 
            - build-node4
            - build-node6
            - build-node8
