version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: sudo npm install -g yarn semantic-release@12.0.0
      - run: yarn install
      - run:
          name: test
          command: |
            mkdir -p ~/reports
            yarn test
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
      - run: semantic-release
      - run: yarn docs
      # needs proper NOW setup first
      # - run: yarn docs:publish
