version: 2
references: 
  run_tests: &run_tests
    steps:
      - checkout
      - run: sudo npm install -g yarn
      - run: yarn install
      - run:
          name: test
          command: |
            mkdir -p ~/reports
            yarn test
      - store_test_results:
          path: ~/reports
          prefix: tests
      - store_artifacts:
          path: ~/reports
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

jobs:
  build-node4:
    docker:
      - image: circleci/node:4@sha256:9611e1ec2f4e0e18765d2e62e4d24e69323b7d9693438ff256c323798a08c346
    <<: *run_tests
  build-node6:
    docker:
      - image: circleci/node:6@sha256:635b022773f0346704312a36d1ce4628e0676a8a2b04e76c15888b67deaeb182
    <<: *run_tests
  build-node8:
    docker:
      - image: circleci/node:latest@sha256:8c909b496d13837354db2855e7fd8563599eb091304bdb7bdbfde0420621fe2f
    <<: *run_tests
  release:
    docker: 
      - image: circleci/node:latest@sha256:8c909b496d13837354db2855e7fd8563599eb091304bdb7bdbfde0420621fe2f
    steps: 
      - checkout
      - run: sudo npm install -g yarn semantic-release@12.0.0
      - run: yarn install
      - run: semantic-release
      - run: yarn docs
      # needs proper NOW setup first
      # - run: yarn docs:publish

workflows:
  version: 2
  build:
    jobs:
      - build-node4
      - build-node6
      - build-node8
      - release:
          requires: 
            - build-node4
            - build-node6
            - build-node8
