version: 2
references: 
  run_tests: &run_tests
    steps:
      - checkout
      - run: sudo npm install -g yarn
      - run: yarn install
      - run:
          name: test
          command: |
            mkdir -p ~/reports
            yarn test
      - store_test_results:
          path: ~/reports
          prefix: tests
      - store_artifacts:
          path: ~/reports
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

jobs:
  build-node4:
    docker:
      - image: circleci/node:4@sha256:952f2fc3d2da7f3261a5890f815061f65137efce6705cae539f6f5db45c2a59b
    <<: *run_tests
  build-node6:
    docker:
      - image: circleci/node:6@sha256:6c64433cd80bb347d5d95fada05743163eacbae3ceebeebfe81ae142d26bc57e
    <<: *run_tests
  build-node8:
    docker:
      - image: circleci/node:latest@sha256:8c909b496d13837354db2855e7fd8563599eb091304bdb7bdbfde0420621fe2f
    <<: *run_tests
  release:
    docker: 
      - image: circleci/node:latest@sha256:8c909b496d13837354db2855e7fd8563599eb091304bdb7bdbfde0420621fe2f
    steps: 
      - checkout
      - run: sudo npm install -g yarn semantic-release@12.0.0
      - run: yarn install
      - run: semantic-release
      - run: yarn docs
      # needs proper NOW setup first
      # - run: yarn docs:publish

workflows:
  version: 2
  build:
    jobs:
      - build-node4
      - build-node6
      - build-node8
      - release:
          requires: 
            - build-node4
            - build-node6
            - build-node8
